name: setonix_api
description: The Linwood Setonix API
version: 0.3.1
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.5.1 <4.0.0"

# Add regular dependencies here.
dependencies:
  dart_mappable: ^4.2.2
  archive: ^4.0.2
  lw_file_system_api:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs.git
      ref: e4c17cb5e3a53c0cd02d4127458c2215f7c6e7d4
      path: packages/lw_file_system_api
  networker:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs.git
      ref: 0bdc62d3af7f31e19a694d9cd39fe020dced8754
      path: packages/networker/networker
  dart_leap:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs.git
      path: packages/dart_leap
      ref: db69a03082e6811c58dc2d0e5c23d04305e1623f
  crypto: ^3.0.5
  collection: ^1.18.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  dart_mappable_builder: ^4.2.3
  build_runner: ^2.4.12
